name: Package exe with PyInstaller - Windows
on: [push, pull_request]

jobs:
  build:
    name: Build exe [${{ matrix.name }}]
    strategy:
      fail-fast: false
      matrix:
        name: [proxySpeedTestApp]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: biplobsd/pyinstaller-action-windows@main
      with:
        path: .
        spec: pyinstaller.spec

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package ${{ matrix.name }}
        path: src/dist/windows
